id: I3BBB5BE5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:00:03+00:00'
last_modified: '2022-06-08T10:10:52.701233+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74456
  title: གསུང་ཐོར་བུ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    029D:
      image_group_id: I4CZ74458
      title: ''
      total_pages: 974
      order: 1
      base_file: 029D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
