id: P009320
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:15.175496
source_metadata:
  id: bdr:W4CZ74456
  title: གསུང་ཐོར་བུ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: ''
  volumes:
    3e9c1f78f30a41c9b645c32c6efb23bc:
      image_group_id: I4CZ74458
      title: ''
      volume_number: 1
      total_pages: 974
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
