id: P009320
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74456
  title: གསུང་ཐོར་བུ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: ''
  volumes:
    3e9c1f78f30a41c9b645c32c6efb23bc:
      image_group_id: I4CZ74458
      title: ''
      volume_number: 1
      total_pages: 974
